/*
 * WCI Automap API
 * API documentation for the West Coast Informatics Automated Term Mapping Service.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@westcoastinformatics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.wci.automap.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Atom
 */
public class AtomTest {
    private final Atom model = new Atom();

    /**
     * Model tests for Atom
     */
    @Test
    public void testAtom() {
        // TODO: test Atom
    }

    /**
     * Test the property 'codeId'
     */
    @Test
    public void codeIdTest() {
        // TODO: test codeId
    }

    /**
     * Test the property 'conceptId'
     */
    @Test
    public void conceptIdTest() {
        // TODO: test conceptId
    }

    /**
     * Test the property 'descriptorId'
     */
    @Test
    public void descriptorIdTest() {
        // TODO: test descriptorId
    }

    /**
     * Test the property 'localeMap'
     */
    @Test
    public void localeMapTest() {
        // TODO: test localeMap
    }

    /**
     * Test the property 'termType'
     */
    @Test
    public void termTypeTest() {
        // TODO: test termType
    }

    /**
     * Test the property 'local'
     */
    @Test
    public void localTest() {
        // TODO: test local
    }

    /**
     * Test the property 'modifiedBy'
     */
    @Test
    public void modifiedByTest() {
        // TODO: test modifiedBy
    }

    /**
     * Test the property 'created'
     */
    @Test
    public void createdTest() {
        // TODO: test created
    }

    /**
     * Test the property 'modified'
     */
    @Test
    public void modifiedTest() {
        // TODO: test modified
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'active'
     */
    @Test
    public void activeTest() {
        // TODO: test active
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'terminologyId'
     */
    @Test
    public void terminologyIdTest() {
        // TODO: test terminologyId
    }

    /**
     * Test the property 'terminology'
     */
    @Test
    public void terminologyTest() {
        // TODO: test terminology
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    public void attributesTest() {
        // TODO: test attributes
    }

}
