/*
 * WCI Automap API
 * API documentation for the West Coast Informatics Automated Term Mapping Service.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@westcoastinformatics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package api.model;

import api.model.Concept;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.UUID;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ConceptTreePosition
 */
public class ConceptTreePositionTest {
    private final ConceptTreePosition model = new ConceptTreePosition();

    /**
     * Model tests for ConceptTreePosition
     */
    @Test
    public void testConceptTreePosition() {
        // TODO: test ConceptTreePosition
    }

    /**
     * Test the property 'children'
     */
    @Test
    public void childrenTest() {
        // TODO: test children
    }

    /**
     * Test the property 'ancestorPath'
     */
    @Test
    public void ancestorPathTest() {
        // TODO: test ancestorPath
    }

    /**
     * Test the property 'childCt'
     */
    @Test
    public void childCtTest() {
        // TODO: test childCt
    }

    /**
     * Test the property 'concept'
     */
    @Test
    public void conceptTest() {
        // TODO: test concept
    }

    /**
     * Test the property 'level'
     */
    @Test
    public void levelTest() {
        // TODO: test level
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'additionalType'
     */
    @Test
    public void additionalTypeTest() {
        // TODO: test additionalType
    }

    /**
     * Test the property 'local'
     */
    @Test
    public void localTest() {
        // TODO: test local
    }

    /**
     * Test the property 'modifiedBy'
     */
    @Test
    public void modifiedByTest() {
        // TODO: test modifiedBy
    }

    /**
     * Test the property 'created'
     */
    @Test
    public void createdTest() {
        // TODO: test created
    }

    /**
     * Test the property 'modified'
     */
    @Test
    public void modifiedTest() {
        // TODO: test modified
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'active'
     */
    @Test
    public void activeTest() {
        // TODO: test active
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'terminology'
     */
    @Test
    public void terminologyTest() {
        // TODO: test terminology
    }

}
