/*
 * WCI Automap API
 * API documentation for the West Coast Informatics Automated Term Mapping Service.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@westcoastinformatics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.wci.automap.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.Date;
import java.util.UUID;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ConceptRelationship
 */
public class ConceptRelationshipTest {
    private final ConceptRelationship model = new ConceptRelationship();

    /**
     * Model tests for ConceptRelationship
     */
    @Test
    public void testConceptRelationship() {
        // TODO: test ConceptRelationship
    }

    /**
     * Test the property 'hierarchical'
     */
    @Test
    public void hierarchicalTest() {
        // TODO: test hierarchical
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'toActive'
     */
    @Test
    public void toActiveTest() {
        // TODO: test toActive
    }

    /**
     * Test the property 'toValue'
     */
    @Test
    public void toValueTest() {
        // TODO: test toValue
    }

    /**
     * Test the property 'group'
     */
    @Test
    public void groupTest() {
        // TODO: test group
    }

    /**
     * Test the property 'toCode'
     */
    @Test
    public void toCodeTest() {
        // TODO: test toCode
    }

    /**
     * Test the property 'toName'
     */
    @Test
    public void toNameTest() {
        // TODO: test toName
    }

    /**
     * Test the property 'toTerminology'
     */
    @Test
    public void toTerminologyTest() {
        // TODO: test toTerminology
    }

    /**
     * Test the property 'assertedDirection'
     */
    @Test
    public void assertedDirectionTest() {
        // TODO: test assertedDirection
    }

    /**
     * Test the property 'additionalType'
     */
    @Test
    public void additionalTypeTest() {
        // TODO: test additionalType
    }

    /**
     * Test the property 'defining'
     */
    @Test
    public void definingTest() {
        // TODO: test defining
    }

    /**
     * Test the property 'local'
     */
    @Test
    public void localTest() {
        // TODO: test local
    }

    /**
     * Test the property 'modifiedBy'
     */
    @Test
    public void modifiedByTest() {
        // TODO: test modifiedBy
    }

    /**
     * Test the property 'created'
     */
    @Test
    public void createdTest() {
        // TODO: test created
    }

    /**
     * Test the property 'modified'
     */
    @Test
    public void modifiedTest() {
        // TODO: test modified
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'active'
     */
    @Test
    public void activeTest() {
        // TODO: test active
    }

    /**
     * Test the property 'terminologyId'
     */
    @Test
    public void terminologyIdTest() {
        // TODO: test terminologyId
    }

    /**
     * Test the property 'terminology'
     */
    @Test
    public void terminologyTest() {
        // TODO: test terminology
    }

}
