/*
 * WCI Automap API
 * API documentation for the West Coast Informatics Automated Term Mapping Service.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@westcoastinformatics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.wci.automap.client.model;

import com.wci.automap.client.model.FormItem;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for QuestionForm
 */
public class QuestionFormTest {
    private final QuestionForm model = new QuestionForm();

    /**
     * Model tests for QuestionForm
     */
    @Test
    public void testQuestionForm() {
        // TODO: test QuestionForm
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'codingInstructions'
     */
    @Test
    public void codingInstructionsTest() {
        // TODO: test codingInstructions
    }

    /**
     * Test the property 'copyrightNotice'
     */
    @Test
    public void copyrightNoticeTest() {
        // TODO: test copyrightNotice
    }

    /**
     * Test the property 'items'
     */
    @Test
    public void itemsTest() {
        // TODO: test items
    }

    /**
     * Test the property 'lformsVersion'
     */
    @Test
    public void lformsVersionTest() {
        // TODO: test lformsVersion
    }

    /**
     * Test the property 'codeSystem'
     */
    @Test
    public void codeSystemTest() {
        // TODO: test codeSystem
    }

}
