/*
 * WCI Automap API
 * API documentation for the West Coast Informatics Automated Term Mapping Service.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@westcoastinformatics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.wci.automap.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.Arrays;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;
import java.util.UUID;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Subset
 */
public class SubsetTest {
    private final Subset model = new Subset();

    /**
     * Model tests for Subset
     */
    @Test
    public void testSubset() {
        // TODO: test Subset
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'scope'
     */
    @Test
    public void scopeTest() {
        // TODO: test scope
    }

    /**
     * Test the property 'generator'
     */
    @Test
    public void generatorTest() {
        // TODO: test generator
    }

    /**
     * Test the property 'memberIds'
     */
    @Test
    public void memberIdsTest() {
        // TODO: test memberIds
    }

    /**
     * Test the property 'editorialPolicy'
     */
    @Test
    public void editorialPolicyTest() {
        // TODO: test editorialPolicy
    }

    /**
     * Test the property 'universeSubset'
     */
    @Test
    public void universeSubsetTest() {
        // TODO: test universeSubset
    }

    /**
     * Test the property 'upgradeGenerator'
     */
    @Test
    public void upgradeGeneratorTest() {
        // TODO: test upgradeGenerator
    }

    /**
     * Test the property 'derivedFromSubset'
     */
    @Test
    public void derivedFromSubsetTest() {
        // TODO: test derivedFromSubset
    }

    /**
     * Test the property 'disjointSubsets'
     */
    @Test
    public void disjointSubsetsTest() {
        // TODO: test disjointSubsets
    }

    /**
     * Test the property 'workflowStatus'
     */
    @Test
    public void workflowStatusTest() {
        // TODO: test workflowStatus
    }

    /**
     * Test the property 'publishable'
     */
    @Test
    public void publishableTest() {
        // TODO: test publishable
    }

    /**
     * Test the property 'descendantsGenerator'
     */
    @Test
    public void descendantsGeneratorTest() {
        // TODO: test descendantsGenerator
    }

    /**
     * Test the property 'referencedSubsetCodes'
     */
    @Test
    public void referencedSubsetCodesTest() {
        // TODO: test referencedSubsetCodes
    }

    /**
     * Test the property 'referencedTerminologyCodes'
     */
    @Test
    public void referencedTerminologyCodesTest() {
        // TODO: test referencedTerminologyCodes
    }

    /**
     * Test the property 'style'
     */
    @Test
    public void styleTest() {
        // TODO: test style
    }

    /**
     * Test the property 'entityType'
     */
    @Test
    public void entityTypeTest() {
        // TODO: test entityType
    }

    /**
     * Test the property 'query'
     */
    @Test
    public void queryTest() {
        // TODO: test query
    }

    /**
     * Test the property 'local'
     */
    @Test
    public void localTest() {
        // TODO: test local
    }

    /**
     * Test the property 'modifiedBy'
     */
    @Test
    public void modifiedByTest() {
        // TODO: test modifiedBy
    }

    /**
     * Test the property 'created'
     */
    @Test
    public void createdTest() {
        // TODO: test created
    }

    /**
     * Test the property 'modified'
     */
    @Test
    public void modifiedTest() {
        // TODO: test modified
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'active'
     */
    @Test
    public void activeTest() {
        // TODO: test active
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'terminology'
     */
    @Test
    public void terminologyTest() {
        // TODO: test terminology
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    public void attributesTest() {
        // TODO: test attributes
    }

}
