/*
 * WCI Automap API
 * API documentation for the West Coast Informatics Automated Term Mapping Service.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@westcoastinformatics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package api;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

import com.wci.automap.client.invoker.ApiException;
import com.wci.automap.client.model.AuthRequest;
import com.wci.automap.client.model.AuthRequest.GrantTypeEnum;
import com.wci.automap.client.model.AuthResponse;

/**
 * API tests for LoginApi
 */
public class LoginApiTest {

    private final LoginApi api = new LoginApi();

    /**
     * Login
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void authTest() throws ApiException {
        // Set up the API client with authentication
        final String username = System.getProperty("username");
        final String password = System.getProperty("password");
        final AuthRequest authRequest = new AuthRequest();
        authRequest.setGrantType(GrantTypeEnum.USERNAME_PASSWORD);
        authRequest.setUsername(username);
        authRequest.setPassword(password);

        try {
            final AuthResponse response = api.auth(authRequest);
            assertNotNull(response);
            assertNotNull(response.getAccessToken());
        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

}
