/*
 * WCI Automap API
 * <p>API documentation for the West Coast Informatics Automated Term Mapping Service.</p><p>For developer documentation and examples, see on GitHub <a href=\"https://github.com/westCoastInformatics/wci-automap-in-5-minutes\">WCI Automap in 5 Minutes</a></p>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@westcoastinformatics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.wci.automap.client;

import com.wci.automap.client.invoker.ApiClient;
import com.wci.automap.client.invoker.ApiException;
import com.wci.automap.client.invoker.ApiResponse;
import com.wci.automap.client.invoker.Pair;

import com.wci.automap.client.model.ApplicationMetadataMap;
import com.wci.automap.client.model.AuditEntry;
import com.wci.automap.client.model.InputTask;
import com.wci.automap.client.model.OutputTask;
import com.wci.automap.client.model.OutputTerm;
import com.wci.automap.client.model.ResultListOutputTask;
import com.wci.automap.client.model.ResultListOutputTerm;
import com.wci.automap.client.model.ResultListString;
import com.wci.automap.client.model.Tag;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-28T10:46:19.010911900-07:00[America/Los_Angeles]", comments = "Generator version: 7.5.0")
public class MappingApi {
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public MappingApi() {
    this(new ApiClient());
  }

  public MappingApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }

  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Add an task to request mapping of included terms
   * &lt;a href&#x3D;\&quot;/examples/index.html\&quot;&gt;Click here&lt;/a&gt; for samples of request and response body.
   * @param inputTask Batch of terms to map (required)
   * @return OutputTask
   * @throws ApiException if fails to make API call
   * Additional sample request and response bodies
   * @see <a href="http://localhost:8082/examples/index.html">Add an task to request mapping of included terms Documentation</a>
   */
  public OutputTask addTask(InputTask inputTask) throws ApiException {
    ApiResponse<OutputTask> localVarResponse = addTaskWithHttpInfo(inputTask);
    return localVarResponse.getData();
  }

  /**
   * Add an task to request mapping of included terms
   * &lt;a href&#x3D;\&quot;/examples/index.html\&quot;&gt;Click here&lt;/a&gt; for samples of request and response body.
   * @param inputTask Batch of terms to map (required)
   * @return ApiResponse&lt;OutputTask&gt;
   * @throws ApiException if fails to make API call
   * Additional sample request and response bodies
   * @see <a href="http://localhost:8082/examples/index.html">Add an task to request mapping of included terms Documentation</a>
   */
  public ApiResponse<OutputTask> addTaskWithHttpInfo(InputTask inputTask) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = addTaskRequestBuilder(inputTask);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("addTask", localVarResponse);
        }
        return new ApiResponse<OutputTask>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<OutputTask>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder addTaskRequestBuilder(InputTask inputTask) throws ApiException {
    // verify the required parameter 'inputTask' is set
    if (inputTask == null) {
      throw new ApiException(400, "Missing the required parameter 'inputTask' when calling addTask");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/mapping/task";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(inputTask);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Find batch set names matching specified parameters
   * 
   * @param query search query, e.g. heart attack (optional)
   * @param offset start index for search results (optional)
   * @param limit limit of results to return (optional)
   * @return ResultListString
   * @throws ApiException if fails to make API call
   */
  public ResultListString findBatchSets(String query, Integer offset, Integer limit) throws ApiException {
    ApiResponse<ResultListString> localVarResponse = findBatchSetsWithHttpInfo(query, offset, limit);
    return localVarResponse.getData();
  }

  /**
   * Find batch set names matching specified parameters
   * 
   * @param query search query, e.g. heart attack (optional)
   * @param offset start index for search results (optional)
   * @param limit limit of results to return (optional)
   * @return ApiResponse&lt;ResultListString&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ResultListString> findBatchSetsWithHttpInfo(String query, Integer offset, Integer limit) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = findBatchSetsRequestBuilder(query, offset, limit);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("findBatchSets", localVarResponse);
        }
        return new ApiResponse<ResultListString>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<ResultListString>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder findBatchSetsRequestBuilder(String query, Integer offset, Integer limit) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/mapping/batch";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "query";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("query", query));
    localVarQueryParameterBaseName = "offset";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("offset", offset));
    localVarQueryParameterBaseName = "limit";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Find tasks matching specified parameters
   * 
   * @param query search query, e.g. heart attack (optional)
   * @param offset start index for search results (optional)
   * @param limit limit of results to return (optional)
   * @param sort comma-separated list of fields to sort on (optional)
   * @param ascending &lt;code&gt;true&lt;/code&gt; for ascending, &lt;code&gt;false&lt;/code&gt; for descending, &lt;code&gt;null&lt;/code&gt; for unspecified (optional)
   * @param batch batch set name, e.g. testBatch12345 (optional)
   * @return ResultListOutputTask
   * @throws ApiException if fails to make API call
   */
  public ResultListOutputTask findTasks(String query, Integer offset, Integer limit, String sort, Boolean ascending, String batch) throws ApiException {
    ApiResponse<ResultListOutputTask> localVarResponse = findTasksWithHttpInfo(query, offset, limit, sort, ascending, batch);
    return localVarResponse.getData();
  }

  /**
   * Find tasks matching specified parameters
   * 
   * @param query search query, e.g. heart attack (optional)
   * @param offset start index for search results (optional)
   * @param limit limit of results to return (optional)
   * @param sort comma-separated list of fields to sort on (optional)
   * @param ascending &lt;code&gt;true&lt;/code&gt; for ascending, &lt;code&gt;false&lt;/code&gt; for descending, &lt;code&gt;null&lt;/code&gt; for unspecified (optional)
   * @param batch batch set name, e.g. testBatch12345 (optional)
   * @return ApiResponse&lt;ResultListOutputTask&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ResultListOutputTask> findTasksWithHttpInfo(String query, Integer offset, Integer limit, String sort, Boolean ascending, String batch) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = findTasksRequestBuilder(query, offset, limit, sort, ascending, batch);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("findTasks", localVarResponse);
        }
        return new ApiResponse<ResultListOutputTask>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<ResultListOutputTask>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder findTasksRequestBuilder(String query, Integer offset, Integer limit, String sort, Boolean ascending, String batch) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/mapping/task";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "query";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("query", query));
    localVarQueryParameterBaseName = "offset";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("offset", offset));
    localVarQueryParameterBaseName = "limit";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));
    localVarQueryParameterBaseName = "sort";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("sort", sort));
    localVarQueryParameterBaseName = "ascending";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("ascending", ascending));
    localVarQueryParameterBaseName = "batch";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("batch", batch));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Find tasks matching specified parameters
   * 
   * @param query search query, e.g. heart attack (optional)
   * @param offset start index for search results (optional)
   * @param limit limit of results to return (optional)
   * @param sort comma-separated list of fields to sort on (optional)
   * @param ascending &lt;code&gt;true&lt;/code&gt; for ascending, &lt;code&gt;false&lt;/code&gt; for descending, &lt;code&gt;null&lt;/code&gt; for unspecified (optional)
   * @param batch batch set name, e.g. testBatch12345 (optional)
   * @return ResultListOutputTerm
   * @throws ApiException if fails to make API call
   */
  public ResultListOutputTerm findTerms(String query, Integer offset, Integer limit, String sort, Boolean ascending, String batch) throws ApiException {
    ApiResponse<ResultListOutputTerm> localVarResponse = findTermsWithHttpInfo(query, offset, limit, sort, ascending, batch);
    return localVarResponse.getData();
  }

  /**
   * Find tasks matching specified parameters
   * 
   * @param query search query, e.g. heart attack (optional)
   * @param offset start index for search results (optional)
   * @param limit limit of results to return (optional)
   * @param sort comma-separated list of fields to sort on (optional)
   * @param ascending &lt;code&gt;true&lt;/code&gt; for ascending, &lt;code&gt;false&lt;/code&gt; for descending, &lt;code&gt;null&lt;/code&gt; for unspecified (optional)
   * @param batch batch set name, e.g. testBatch12345 (optional)
   * @return ApiResponse&lt;ResultListOutputTerm&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ResultListOutputTerm> findTermsWithHttpInfo(String query, Integer offset, Integer limit, String sort, Boolean ascending, String batch) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = findTermsRequestBuilder(query, offset, limit, sort, ascending, batch);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("findTerms", localVarResponse);
        }
        return new ApiResponse<ResultListOutputTerm>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<ResultListOutputTerm>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder findTermsRequestBuilder(String query, Integer offset, Integer limit, String sort, Boolean ascending, String batch) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/mapping/term";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "query";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("query", query));
    localVarQueryParameterBaseName = "offset";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("offset", offset));
    localVarQueryParameterBaseName = "limit";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));
    localVarQueryParameterBaseName = "sort";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("sort", sort));
    localVarQueryParameterBaseName = "ascending";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("ascending", ascending));
    localVarQueryParameterBaseName = "batch";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("batch", batch));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get entity configuration
   * 
   * @return ApplicationMetadataMap
   * @throws ApiException if fails to make API call
   */
  public ApplicationMetadataMap getEntityConfig() throws ApiException {
    ApiResponse<ApplicationMetadataMap> localVarResponse = getEntityConfigWithHttpInfo();
    return localVarResponse.getData();
  }

  /**
   * Get entity configuration
   * 
   * @return ApiResponse&lt;ApplicationMetadataMap&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ApplicationMetadataMap> getEntityConfigWithHttpInfo() throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getEntityConfigRequestBuilder();
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getEntityConfig", localVarResponse);
        }
        return new ApiResponse<ApplicationMetadataMap>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<ApplicationMetadataMap>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getEntityConfigRequestBuilder() throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/mapping/config";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get application metadata
   * 
   * @return ApplicationMetadataMap
   * @throws ApiException if fails to make API call
   */
  public ApplicationMetadataMap getMetadata() throws ApiException {
    ApiResponse<ApplicationMetadataMap> localVarResponse = getMetadataWithHttpInfo();
    return localVarResponse.getData();
  }

  /**
   * Get application metadata
   * 
   * @return ApiResponse&lt;ApplicationMetadataMap&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ApplicationMetadataMap> getMetadataWithHttpInfo() throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getMetadataRequestBuilder();
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getMetadata", localVarResponse);
        }
        return new ApiResponse<ApplicationMetadataMap>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<ApplicationMetadataMap>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getMetadataRequestBuilder() throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/mapping/metadata";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get task object for the specified task id
   * 
   * @param taskId  (required)
   * @return OutputTask
   * @throws ApiException if fails to make API call
   */
  public OutputTask getTask(String taskId) throws ApiException {
    ApiResponse<OutputTask> localVarResponse = getTaskWithHttpInfo(taskId);
    return localVarResponse.getData();
  }

  /**
   * Get task object for the specified task id
   * 
   * @param taskId  (required)
   * @return ApiResponse&lt;OutputTask&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<OutputTask> getTaskWithHttpInfo(String taskId) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getTaskRequestBuilder(taskId);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getTask", localVarResponse);
        }
        return new ApiResponse<OutputTask>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<OutputTask>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getTaskRequestBuilder(String taskId) throws ApiException {
    // verify the required parameter 'taskId' is set
    if (taskId == null) {
      throw new ApiException(400, "Missing the required parameter 'taskId' when calling getTask");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/mapping/task/{taskId}"
        .replace("{taskId}", ApiClient.urlEncode(taskId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get term for the specified taskId and termId
   * 
   * @param taskId task.id returned by /task/add, e.g. 642c0e8a-8bdc-4ae6-8773-9f6cd8bc2fd3 (required)
   * @param termId term.id, e.g. 8271f5b9-ee2a-4614-87a1-2c071c9d6076 (required)
   * @return OutputTerm
   * @throws ApiException if fails to make API call
   */
  public OutputTerm getTaskTerm(String taskId, String termId) throws ApiException {
    ApiResponse<OutputTerm> localVarResponse = getTaskTermWithHttpInfo(taskId, termId);
    return localVarResponse.getData();
  }

  /**
   * Get term for the specified taskId and termId
   * 
   * @param taskId task.id returned by /task/add, e.g. 642c0e8a-8bdc-4ae6-8773-9f6cd8bc2fd3 (required)
   * @param termId term.id, e.g. 8271f5b9-ee2a-4614-87a1-2c071c9d6076 (required)
   * @return ApiResponse&lt;OutputTerm&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<OutputTerm> getTaskTermWithHttpInfo(String taskId, String termId) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getTaskTermRequestBuilder(taskId, termId);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getTaskTerm", localVarResponse);
        }
        return new ApiResponse<OutputTerm>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<OutputTerm>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getTaskTermRequestBuilder(String taskId, String termId) throws ApiException {
    // verify the required parameter 'taskId' is set
    if (taskId == null) {
      throw new ApiException(400, "Missing the required parameter 'taskId' when calling getTaskTerm");
    }
    // verify the required parameter 'termId' is set
    if (termId == null) {
      throw new ApiException(400, "Missing the required parameter 'termId' when calling getTaskTerm");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/mapping/task/{taskId}/term/{termId}"
        .replace("{taskId}", ApiClient.urlEncode(taskId.toString()))
        .replace("{termId}", ApiClient.urlEncode(termId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get audit trail for the specified taskId and termId
   * 
   * @param taskId task.id returned by /task/add, e.g. 642c0e8a-8bdc-4ae6-8773-9f6cd8bc2fd3 (required)
   * @param termId term.id, e.g. 8271f5b9-ee2a-4614-87a1-2c071c9d6076 (required)
   * @return List&lt;AuditEntry&gt;
   * @throws ApiException if fails to make API call
   */
  public List<AuditEntry> getTaskTermAuditTrail(String taskId, String termId) throws ApiException {
    ApiResponse<List<AuditEntry>> localVarResponse = getTaskTermAuditTrailWithHttpInfo(taskId, termId);
    return localVarResponse.getData();
  }

  /**
   * Get audit trail for the specified taskId and termId
   * 
   * @param taskId task.id returned by /task/add, e.g. 642c0e8a-8bdc-4ae6-8773-9f6cd8bc2fd3 (required)
   * @param termId term.id, e.g. 8271f5b9-ee2a-4614-87a1-2c071c9d6076 (required)
   * @return ApiResponse&lt;List&lt;AuditEntry&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<AuditEntry>> getTaskTermAuditTrailWithHttpInfo(String taskId, String termId) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getTaskTermAuditTrailRequestBuilder(taskId, termId);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getTaskTermAuditTrail", localVarResponse);
        }
        return new ApiResponse<List<AuditEntry>>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<List<AuditEntry>>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getTaskTermAuditTrailRequestBuilder(String taskId, String termId) throws ApiException {
    // verify the required parameter 'taskId' is set
    if (taskId == null) {
      throw new ApiException(400, "Missing the required parameter 'taskId' when calling getTaskTermAuditTrail");
    }
    // verify the required parameter 'termId' is set
    if (termId == null) {
      throw new ApiException(400, "Missing the required parameter 'termId' when calling getTaskTermAuditTrail");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/mapping/task/{taskId}/term/{termId}/audit"
        .replace("{taskId}", ApiClient.urlEncode(taskId.toString()))
        .replace("{termId}", ApiClient.urlEncode(termId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get version information for components of the application
   * 
   * @return List&lt;Tag&gt;
   * @throws ApiException if fails to make API call
   */
  public List<Tag> getVersions() throws ApiException {
    ApiResponse<List<Tag>> localVarResponse = getVersionsWithHttpInfo();
    return localVarResponse.getData();
  }

  /**
   * Get version information for components of the application
   * 
   * @return ApiResponse&lt;List&lt;Tag&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<Tag>> getVersionsWithHttpInfo() throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getVersionsRequestBuilder();
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getVersions", localVarResponse);
        }
        return new ApiResponse<List<Tag>>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<List<Tag>>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getVersionsRequestBuilder() throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/mapping/version";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Map codes in a FHIR R4 document
   * Takes a FHIR R4 document (resource or bundle) and returns it with suggested codes.
   * @param body  (required)
   * @param audit indicates whether or not to audit the maps (optional)
   * @param minConfidence all results will have confidence above this value (optional)
   * @param maxResults maximum number of results to return (optional)
   * @return String
   * @throws ApiException if fails to make API call
   */
  public String mapFhir(String body, Boolean audit, Double minConfidence, Integer maxResults) throws ApiException {
    ApiResponse<String> localVarResponse = mapFhirWithHttpInfo(body, audit, minConfidence, maxResults);
    return localVarResponse.getData();
  }

  /**
   * Map codes in a FHIR R4 document
   * Takes a FHIR R4 document (resource or bundle) and returns it with suggested codes.
   * @param body  (required)
   * @param audit indicates whether or not to audit the maps (optional)
   * @param minConfidence all results will have confidence above this value (optional)
   * @param maxResults maximum number of results to return (optional)
   * @return ApiResponse&lt;String&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<String> mapFhirWithHttpInfo(String body, Boolean audit, Double minConfidence, Integer maxResults) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = mapFhirRequestBuilder(body, audit, minConfidence, maxResults);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("mapFhir", localVarResponse);
        }
        return new ApiResponse<String>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<String>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder mapFhirRequestBuilder(String body, Boolean audit, Double minConfidence, Integer maxResults) throws ApiException {
    // verify the required parameter 'body' is set
    if (body == null) {
      throw new ApiException(400, "Missing the required parameter 'body' when calling mapFhir");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/mapping/fhir";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "audit";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("audit", audit));
    localVarQueryParameterBaseName = "minConfidence";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("minConfidence", minConfidence));
    localVarQueryParameterBaseName = "maxResults";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("maxResults", maxResults));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Content-Type", "application/fhir+json");
    localVarRequestBuilder.header("Accept", "application/fhir+json, application/json");

    localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofString(body));
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
