/*
 * WCI Automap API
 * <p>API documentation for the West Coast Informatics Automated Term Mapping Service.</p><p>For developer documentation and examples, see on GitHub <a href=\"https://github.com/westCoastInformatics/wci-automap-in-5-minutes\">WCI Automap in 5 Minutes</a></p>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@westcoastinformatics.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.wci.automap.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.wci.automap.client.model.Tag;
import com.wci.automap.client.model.TermMapping;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Represents an fully mapped term with attached mappings
 */
@JsonPropertyOrder({
  OutputTerm.JSON_PROPERTY_MAPPINGS,
  OutputTerm.JSON_PROPERTY_STATUS,
  OutputTerm.JSON_PROPERTY_MESSAGE,
  OutputTerm.JSON_PROPERTY_CONFIDENCE,
  OutputTerm.JSON_PROPERTY_MAPPING_CT,
  OutputTerm.JSON_PROPERTY_CODE,
  OutputTerm.JSON_PROPERTY_INPUT_TYPE,
  OutputTerm.JSON_PROPERTY_CONTEXT,
  OutputTerm.JSON_PROPERTY_TERM,
  OutputTerm.JSON_PROPERTY_TERMINOLOGY,
  OutputTerm.JSON_PROPERTY_TASK_ID,
  OutputTerm.JSON_PROPERTY_ENTITY_TYPE,
  OutputTerm.JSON_PROPERTY_TO_TERMINOLOGY,
  OutputTerm.JSON_PROPERTY_MODIFIED_BY,
  OutputTerm.JSON_PROPERTY_CREATED,
  OutputTerm.JSON_PROPERTY_MODIFIED,
  OutputTerm.JSON_PROPERTY_ID,
  OutputTerm.JSON_PROPERTY_TAGS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-28T10:46:19.010911900-07:00[America/Los_Angeles]", comments = "Generator version: 7.5.0")
public class OutputTerm {
  public static final String JSON_PROPERTY_MAPPINGS = "mappings";
  private List<TermMapping> mappings = new ArrayList<>();

  /**
   * Status of the mapping of this term.  Allowable values are detailed by the application metadata endpoint
   */
  public enum StatusEnum {
    FINAL("final"),
    
    PROVISIONAL("provisional"),
    
    OUT_OF_SCOPE("out_of_scope"),
    
    CONFLICT("conflict"),
    
    ERROR("error");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  private StatusEnum status;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  private String message;

  public static final String JSON_PROPERTY_CONFIDENCE = "confidence";
  private Double confidence;

  public static final String JSON_PROPERTY_MAPPING_CT = "mappingCt";
  private Integer mappingCt;

  public static final String JSON_PROPERTY_CODE = "code";
  private String code;

  /**
   * Expected input type of the thing being mapped.  Allowable values are detailed by the application metadata endpoint
   */
  public enum InputTypeEnum {
    PICKLIST("picklist"),
    
    BOOLEAN("boolean"),
    
    STRING("string"),
    
    PHRASE("phrase"),
    
    FHIRCODING("fhirCoding");

    private String value;

    InputTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static InputTypeEnum fromValue(String value) {
      for (InputTypeEnum b : InputTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_INPUT_TYPE = "inputType";
  private InputTypeEnum inputType;

  public static final String JSON_PROPERTY_CONTEXT = "context";
  private Map<String, String> context = new HashMap<>();

  public static final String JSON_PROPERTY_TERM = "term";
  private String term;

  public static final String JSON_PROPERTY_TERMINOLOGY = "terminology";
  private String terminology;

  public static final String JSON_PROPERTY_TASK_ID = "taskId";
  private String taskId;

  /**
   * Expected entity type to be mapped to.  Allowable values are detailed by the application metadata endpoint
   */
  public enum EntityTypeEnum {
    GENERAL("general"),
    
    ALLERGY("allergy"),
    
    BODYPART("bodyPart"),
    
    DEVICE("device"),
    
    CONDITION("condition"),
    
    FAMILYHISTORY("familyHistory"),
    
    IMMUNIZATION("immunization"),
    
    MEDICATION("medication"),
    
    LABRESULT("labResult"),
    
    LABRESULTUNIT("labResultUnit"),
    
    LABRESULTVALUE("labResultValue"),
    
    LABRESULTINTERPRETATION("labResultInterpretation"),
    
    PROCEDURE("procedure"),
    
    SOCIALHISTORY("socialHistory"),
    
    SUBSTANCE("substance"),
    
    VITALSIGN("vitalSign"),
    
    VITALSIGNUNIT("vitalSignUnit"),
    
    VITALSIGNVALUE("vitalSignValue"),
    
    VITALSIGNINTERPRETATION("vitalSignInterpretation"),
    
    BIOMARKER("biomarker"),
    
    COURSE("course"),
    
    GENDER("gender"),
    
    GRADE("grade"),
    
    HISTOLOGY("histology"),
    
    LINEOFTHERAPY("lineOfTherapy"),
    
    PERFORMANCESTATUS("performanceStatus"),
    
    SEVERITY("severity"),
    
    STAGE("stage"),
    
    TUMORSETTING("tumorSetting"),
    
    UNIT("unit"),
    
    CONDITIONCLINICALSTATUS("conditionClinicalStatus"),
    
    CONDITIONVERIFICATIONSTATUS("conditionVerificationStatus"),
    
    CONDITIONCATEGORY("conditionCategory"),
    
    MEDICATIONSTATUS("medicationStatus"),
    
    MEDICATIONDOSEFORM("medicationDoseForm"),
    
    PROCEDURESTATUS("procedureStatus"),
    
    PROCEDURECATEGORY("procedureCategory"),
    
    OBSERVATIONSTATUS("observationStatus"),
    
    OBSERVATIONCATEGORY("observationCategory"),
    
    ALLERGYCLINICALSTATUS("allergyClinicalStatus"),
    
    ALLERGYVERIFICATIONSTATUS("allergyVerificationStatus"),
    
    ALLERGYTYPE("allergyType"),
    
    ALLERGYCATEGORY("allergyCategory"),
    
    ALLERGYCRITICALITY("allergyCriticality"),
    
    ADVERSEEVENT("adverseEvent"),
    
    BIOMARKERINTERPRETATION("biomarkerInterpretation"),
    
    BIOMARKERMETHOD("biomarkerMethod"),
    
    BIOMARKERRESULT("biomarkerResult"),
    
    DOSEFORM("doseForm"),
    
    LABORDER("labOrder"),
    
    LABPANEL("labPanel"),
    
    SYMPTOM("symptom"),
    
    MULTI("multi"),
    
    OTHER("other");

    private String value;

    EntityTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static EntityTypeEnum fromValue(String value) {
      for (EntityTypeEnum b : EntityTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ENTITY_TYPE = "entityType";
  private EntityTypeEnum entityType;

  public static final String JSON_PROPERTY_TO_TERMINOLOGY = "toTerminology";
  private String toTerminology;

  public static final String JSON_PROPERTY_MODIFIED_BY = "modifiedBy";
  private String modifiedBy;

  public static final String JSON_PROPERTY_CREATED = "created";
  private Date created;

  public static final String JSON_PROPERTY_MODIFIED = "modified";
  private Date modified;

  public static final String JSON_PROPERTY_ID = "id";
  private UUID id;

  public static final String JSON_PROPERTY_TAGS = "tags";
  private List<Tag> tags = new ArrayList<>();

  public OutputTerm() { 
  }

  public OutputTerm mappings(List<TermMapping> mappings) {
    this.mappings = mappings;
    return this;
  }

  public OutputTerm addMappingsItem(TermMapping mappingsItem) {
    if (this.mappings == null) {
      this.mappings = new ArrayList<>();
    }
    this.mappings.add(mappingsItem);
    return this;
  }

   /**
   * Computed mappings for this term
   * @return mappings
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MAPPINGS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<TermMapping> getMappings() {
    return mappings;
  }


  @JsonProperty(JSON_PROPERTY_MAPPINGS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMappings(List<TermMapping> mappings) {
    this.mappings = mappings;
  }


  public OutputTerm status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Status of the mapping of this term.  Allowable values are detailed by the application metadata endpoint
   * @return status
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  public OutputTerm message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMessage() {
    return message;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessage(String message) {
    this.message = message;
  }


  public OutputTerm confidence(Double confidence) {
    this.confidence = confidence;
    return this;
  }

   /**
   * Confidence level related to find operation
   * @return confidence
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONFIDENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getConfidence() {
    return confidence;
  }


  @JsonProperty(JSON_PROPERTY_CONFIDENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConfidence(Double confidence) {
    this.confidence = confidence;
  }


  public OutputTerm mappingCt(Integer mappingCt) {
    this.mappingCt = mappingCt;
    return this;
  }

   /**
   * Number of computed mappings for the term
   * @return mappingCt
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MAPPING_CT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getMappingCt() {
    return mappingCt;
  }


  @JsonProperty(JSON_PROPERTY_MAPPING_CT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMappingCt(Integer mappingCt) {
    this.mappingCt = mappingCt;
  }


  public OutputTerm code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Code for the term to be mapped, e.g. \&quot;56265001\&quot;
   * @return code
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCode() {
    return code;
  }


  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCode(String code) {
    this.code = code;
  }


  public OutputTerm inputType(InputTypeEnum inputType) {
    this.inputType = inputType;
    return this;
  }

   /**
   * Expected input type of the thing being mapped.  Allowable values are detailed by the application metadata endpoint
   * @return inputType
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INPUT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public InputTypeEnum getInputType() {
    return inputType;
  }


  @JsonProperty(JSON_PROPERTY_INPUT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInputType(InputTypeEnum inputType) {
    this.inputType = inputType;
  }


  public OutputTerm context(Map<String, String> context) {
    this.context = context;
    return this;
  }

  public OutputTerm putContextItem(String key, String contextItem) {
    if (this.context == null) {
      this.context = new HashMap<>();
    }
    this.context.put(key, contextItem);
    return this;
  }

   /**
   * Additional textual context for disambiguation, including other text around the text of the term
   * @return context
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getContext() {
    return context;
  }


  @JsonProperty(JSON_PROPERTY_CONTEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContext(Map<String, String> context) {
    this.context = context;
  }


  public OutputTerm term(String term) {
    this.term = term;
    return this;
  }

   /**
   * Text value to be mapped, e.g. \&quot;heart disease\&quot;
   * @return term
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TERM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTerm() {
    return term;
  }


  @JsonProperty(JSON_PROPERTY_TERM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTerm(String term) {
    this.term = term;
  }


  public OutputTerm terminology(String terminology) {
    this.terminology = terminology;
    return this;
  }

   /**
   * Terminology for the term to be mapped, e.g. \&quot;SNOMEDCT\&quot; or \&quot;https://loinc.org\&quot;
   * @return terminology
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TERMINOLOGY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTerminology() {
    return terminology;
  }


  @JsonProperty(JSON_PROPERTY_TERMINOLOGY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTerminology(String terminology) {
    this.terminology = terminology;
  }


  public OutputTerm taskId(String taskId) {
    this.taskId = taskId;
    return this;
  }

   /**
   * Task id for this term
   * @return taskId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TASK_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTaskId() {
    return taskId;
  }


  @JsonProperty(JSON_PROPERTY_TASK_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTaskId(String taskId) {
    this.taskId = taskId;
  }


  public OutputTerm entityType(EntityTypeEnum entityType) {
    this.entityType = entityType;
    return this;
  }

   /**
   * Expected entity type to be mapped to.  Allowable values are detailed by the application metadata endpoint
   * @return entityType
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENTITY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EntityTypeEnum getEntityType() {
    return entityType;
  }


  @JsonProperty(JSON_PROPERTY_ENTITY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEntityType(EntityTypeEnum entityType) {
    this.entityType = entityType;
  }


  public OutputTerm toTerminology(String toTerminology) {
    this.toTerminology = toTerminology;
    return this;
  }

   /**
   * Terminology of the term to map to, e.g. \&quot;SNOMEDCT\&quot; or \&quot;https://loinc.org\&quot;. Leave blank for all available options specified by config.
   * @return toTerminology
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TO_TERMINOLOGY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getToTerminology() {
    return toTerminology;
  }


  @JsonProperty(JSON_PROPERTY_TO_TERMINOLOGY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToTerminology(String toTerminology) {
    this.toTerminology = toTerminology;
  }


  public OutputTerm modifiedBy(String modifiedBy) {
    this.modifiedBy = modifiedBy;
    return this;
  }

   /**
   * the identifier of the user who made the last modification
   * @return modifiedBy
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MODIFIED_BY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getModifiedBy() {
    return modifiedBy;
  }


  @JsonProperty(JSON_PROPERTY_MODIFIED_BY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModifiedBy(String modifiedBy) {
    this.modifiedBy = modifiedBy;
  }


  public OutputTerm created(Date created) {
    this.created = created;
    return this;
  }

   /**
   * the created date
   * @return created
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Date getCreated() {
    return created;
  }


  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreated(Date created) {
    this.created = created;
  }


  public OutputTerm modified(Date modified) {
    this.modified = modified;
    return this;
  }

   /**
   * the last modified date
   * @return modified
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MODIFIED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Date getModified() {
    return modified;
  }


  @JsonProperty(JSON_PROPERTY_MODIFIED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModified(Date modified) {
    this.modified = modified;
  }


  public OutputTerm id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * the unique identifier
   * @return id
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(UUID id) {
    this.id = id;
  }


  public OutputTerm tags(List<Tag> tags) {
    this.tags = tags;
    return this;
  }

  public OutputTerm addTagsItem(Tag tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * List of key/value tags
   * @return tags
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Tag> getTags() {
    return tags;
  }


  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(List<Tag> tags) {
    this.tags = tags;
  }


  /**
   * Return true if this OutputTerm object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OutputTerm outputTerm = (OutputTerm) o;
    return Objects.equals(this.mappings, outputTerm.mappings) &&
        Objects.equals(this.status, outputTerm.status) &&
        Objects.equals(this.message, outputTerm.message) &&
        Objects.equals(this.confidence, outputTerm.confidence) &&
        Objects.equals(this.mappingCt, outputTerm.mappingCt) &&
        Objects.equals(this.code, outputTerm.code) &&
        Objects.equals(this.inputType, outputTerm.inputType) &&
        Objects.equals(this.context, outputTerm.context) &&
        Objects.equals(this.term, outputTerm.term) &&
        Objects.equals(this.terminology, outputTerm.terminology) &&
        Objects.equals(this.taskId, outputTerm.taskId) &&
        Objects.equals(this.entityType, outputTerm.entityType) &&
        Objects.equals(this.toTerminology, outputTerm.toTerminology) &&
        Objects.equals(this.modifiedBy, outputTerm.modifiedBy) &&
        Objects.equals(this.created, outputTerm.created) &&
        Objects.equals(this.modified, outputTerm.modified) &&
        Objects.equals(this.id, outputTerm.id) &&
        Objects.equals(this.tags, outputTerm.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mappings, status, message, confidence, mappingCt, code, inputType, context, term, terminology, taskId, entityType, toTerminology, modifiedBy, created, modified, id, tags);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OutputTerm {\n");
    sb.append("    mappings: ").append(toIndentedString(mappings)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    confidence: ").append(toIndentedString(confidence)).append("\n");
    sb.append("    mappingCt: ").append(toIndentedString(mappingCt)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    inputType: ").append(toIndentedString(inputType)).append("\n");
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    term: ").append(toIndentedString(term)).append("\n");
    sb.append("    terminology: ").append(toIndentedString(terminology)).append("\n");
    sb.append("    taskId: ").append(toIndentedString(taskId)).append("\n");
    sb.append("    entityType: ").append(toIndentedString(entityType)).append("\n");
    sb.append("    toTerminology: ").append(toIndentedString(toTerminology)).append("\n");
    sb.append("    modifiedBy: ").append(toIndentedString(modifiedBy)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `mappings` to the URL query string
    if (getMappings() != null) {
      for (int i = 0; i < getMappings().size(); i++) {
        if (getMappings().get(i) != null) {
          joiner.add(getMappings().get(i).toUrlQueryString(String.format("%smappings%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format("%sstatus%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getStatus()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `message` to the URL query string
    if (getMessage() != null) {
      joiner.add(String.format("%smessage%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMessage()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `confidence` to the URL query string
    if (getConfidence() != null) {
      joiner.add(String.format("%sconfidence%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getConfidence()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `mappingCt` to the URL query string
    if (getMappingCt() != null) {
      joiner.add(String.format("%smappingCt%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMappingCt()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `code` to the URL query string
    if (getCode() != null) {
      joiner.add(String.format("%scode%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCode()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `inputType` to the URL query string
    if (getInputType() != null) {
      joiner.add(String.format("%sinputType%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getInputType()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `context` to the URL query string
    if (getContext() != null) {
      for (String _key : getContext().keySet()) {
        joiner.add(String.format("%scontext%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, _key, containerSuffix),
            getContext().get(_key), URLEncoder.encode(String.valueOf(getContext().get(_key)), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
      }
    }

    // add `term` to the URL query string
    if (getTerm() != null) {
      joiner.add(String.format("%sterm%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTerm()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `terminology` to the URL query string
    if (getTerminology() != null) {
      joiner.add(String.format("%sterminology%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTerminology()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `taskId` to the URL query string
    if (getTaskId() != null) {
      joiner.add(String.format("%staskId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTaskId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `entityType` to the URL query string
    if (getEntityType() != null) {
      joiner.add(String.format("%sentityType%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getEntityType()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `toTerminology` to the URL query string
    if (getToTerminology() != null) {
      joiner.add(String.format("%stoTerminology%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getToTerminology()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `modifiedBy` to the URL query string
    if (getModifiedBy() != null) {
      joiner.add(String.format("%smodifiedBy%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getModifiedBy()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `created` to the URL query string
    if (getCreated() != null) {
      joiner.add(String.format("%screated%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCreated()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `modified` to the URL query string
    if (getModified() != null) {
      joiner.add(String.format("%smodified%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getModified()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format("%sid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `tags` to the URL query string
    if (getTags() != null) {
      for (int i = 0; i < getTags().size(); i++) {
        if (getTags().get(i) != null) {
          joiner.add(getTags().get(i).toUrlQueryString(String.format("%stags%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

